### ISSUE TITLE
example/ui.rs ui_state.value have the same name with ResMut.value, causing lint reporting error.

### ISSUE THREAD

**Issue by iamabigartist** [mvlabat/bevy_egui#137] opened 2022-12-04 18:28 UTC
bevy_egui = "0.17.1"

Though it's able to be compiled, ui.rs at line 124, Clippy report: mismatched types [E0308] expected `RangeInclusive<&mut UiState>`, found `RangeInclusive<f64>`.

This is probably because UiState.value has the same name as ResMut<T>.value. Change UiState.value to UiState.value_1 solves the error.

**Comment by mvlabat** [comment] 2023-01-15 18:19
Thanks for the issue. I believe it was fixed in `0.18.0`, can't reproduce it now. I'll close it, but let me know if can still see it (and your `rustc` and `clippy` versions).

**Closed by mvlabat** 2023-01-15 18:19 UTC
