### ISSUE TITLE
Egui crashes with "no entry found for key"

### ISSUE THREAD

**Issue by OfficialURL** [mvlabat/bevy_egui#19] opened 2021-04-27 18:31 UTC
Today I tried updating both `bevy` and `bevy_egui` to their latest versions. Suddenly, in my UI system, I can no longer get the context for the primary window. The code looks like this:

```rust
pub fn ui(
    egui_ctx: ResMut<EguiContext>,
    // other stuff...
) {
    let ctx = egui_ctx.ctx(); // crashes
    
    // other stuff...
}
```

Oddly enough the example code seems to work just fine. I have no idea which interactions within the code might be causing the crash. I can upload the full code if it helps.

**Comment by mvlabat** [comment] 2021-04-28 06:23
Hi! Some reproducible example, even if it's large, would be great. And any details about the building process and the reproduce if it's not just `cargo run` and a crash on start up.
Thanks!

**Comment by mvlabat** [comment] 2021-04-28 06:32
My initial guess is that your system runs before the initial stage of bevy_egui that lets it initialize. You could try running your system after this label: https://github.com/mvlabat/bevy_egui/blob/main/src/lib.rs#L364

or after the `CoreStage::PreUpdate` stage.

**Comment by OfficialURL** [comment] 2021-04-28 06:45
Indeed, it stops crashing after switching the systems involving the UI to the `CoreStage::Update` stage. This seems to be a breaking change from the previous version (I had a system updating the scale factor running fine in `stage::PRE_UPDATE`), so it might be worth documenting somewhere.

Leaving the [code](https://github.com/OfficialURL/miratope-rs/commit/514d91762c7a08b324cd343eeb3c5b28a1b37613#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcL118) for reference (the relevant stage code is at line 99 in `main.rs`).

**Comment by jakobhellermann** [comment] 2021-05-01 11:25
The issue seems to be that before there was only one primary egui context which is always defined. Now there is a hashmap which is lazily populated by the `begin_frame` system. Fixing this should easily possible by initializing the egui context with the primary context already in the hashmap.

**Comment by jakobhellermann** [comment] 2021-05-01 11:28
@OfficialURL can you try if #21 fixes your problem?

**Comment by mvlabat** [comment] 2021-05-02 23:17
@jakobhellermann thanks for the suggested fix. I'm also wondering, whether running any system that renders anything before `EguiSystem::BeginFrame` is going to work, in regards to reading inputs and so on. Your suggestion indeed fixes the case with unavailable primary window context.. but I'm thinking, what if we always panic if any system tries to access the context before it's made available, like a runtime assertion.

**Comment by jakobhellermann** [comment] 2021-05-03 10:10
Any system running before `BeginFrame` panics with ``Called `available_rect()` before `CtxRef::begin_frame()`` anyways even with my 'fix' in #21. I agree that panicking if a system runs before `ProcessInput` is fine, but the error message should be better.

If someone wants to run their UI in `PreUpdate` they can still do it using `.after(EguiSystem::BeginFrame)`.

**Comment by mvlabat** [comment] 2021-05-03 15:34
Version 0.4.2 has just been released with a better error message if `CtxRef` doesn't exist. Thanks, @OfficialURL for bringing this up and @jakobhellermann for making the PRs.

**Closed by mvlabat** 2021-05-03 15:34 UTC

**Comment by OfficialURL** [comment] 2021-05-03 18:17
Tried my failing code on `bevy-egui` 0.4.2, and I indeed get the helpful error message. Thanks!
