### ISSUE TITLE
The `side_panel` example doesn't exit successfully on Windows (must use `Ctrl + C` to exit)

### ISSUE THREAD

**Issue by jonmsawyer** [mvlabat/bevy_egui#118] opened 2022-08-03 07:23 UTC
The `side_panel` example doesn't exit successfully when closed with the icon menu at the top left of the window or by clicking the `X` at the top right of the window. The console sits and waits until I press `Ctrl + C`.

Run with: `cargo run --example side_panel`

Environment:
* Windows 10
  * Edition: Windows 10 Pro
  * Version: 21H2
  * OS build: 19044.1826
  * Experience: Windows Feature Experience Pack 120.2212.4180.0
* Rust
  * rustc 1.62.1 (e092d0b6b 2022-07-16)
* Bevy v0.8
* bevy_egui v0.15

**Comment by mvlabat** [comment] 2022-08-06 11:18
It's a bug in Bevy 0.8 caused by power-saving settings. I forgot to remove them from that particular example. Fixed in 5e31c9e584a7470b940ec45a136dddedf7e930b6, thanks!

**Closed by mvlabat** 2022-08-06 11:18 UTC
