### ISSUE TITLE
gfx_backend_vulkan error

### ISSUE THREAD

**Issue by RichMQ** [mvlabat/bevy_egui#42] opened 2021-10-04 09:27 UTC
I have just added `env_logger::init();` to the `simple.rs` example and I'm getting the following message every frame:
```
[2021-10-04T09:17:50Z ERROR gfx_backend_vulkan]
    VALIDATION [UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress (-400166253)] : Validation Error: [ UNASSIGNED-CoreValidation-DrawState-QueueForwardProgress ] Object 0: handle = 0xea7170000000031, type = VK_OBJECT_TYPE_SEMAPHORE; Object 1: handle = 0x1e5f980a668, type = VK_OBJECT_TYPE_QUEUE; Object 2: handle = 0x1e5f980a668, type = VK_OBJECT_TYPE_QUEUE; | MessageID = 0xe825f293 | vkQueueSubmit(): pSubmits[0].pSignalSemaphores[0] is signaling VkQueue 0x1e5f980a668[] (VkSemaphore 0xea7170000000031[]) that was previously signaled by VkQueue 0x1e5f980a668[] but has not since been waited on by any queue.
    object info: (type: SEMAPHORE, hndl: 1055837926409109553), (type: QUEUE, hndl: 2087245096552), (type: QUEUE, hndl: 2087245096552)
```
Here's my setup.
Dependencies:
```
bevy = "0.5.0"
bevy_egui = "0.7.0"
env_logger = "0.9.0"
```
compiler: rustc 1.57.0-nightly (9dbb26efe 2021-10-03)
OS: Windows 10
GPU: GeForce GTX 1050 Ti
GPU driver: NVIDIA 472.12

Let me know if I can provide any further information to help reproduce.

**Comment by mvlabat** [comment] 2021-10-04 10:17
When I last enabled logging in Bevy, I remember it throwing Vulkan errors as well, and if I'm not mistaken I even tried it without `bevy_egui`. Could you double-check that `bevy_egui` indeed causes it? If it does, I'll definitely look into it.

**Comment by RichMQ** [comment] 2021-10-04 10:52
Oh, yes. I should have mentioned that. By itself, bevy doesn't show any of these errors.

**Comment by mvlabat** [comment] 2021-10-04 17:30
Hmm, strange, I can't reproduce it. If I enable logging in the `simple.rs` example, I get only the following validation error:

```
[2021-10-04T17:26:42Z ERROR gfx_backend_vulkan] 
    VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-04627 (1158829633)] : Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-04627 ] Object 0: handle = 0xb991fa0000000024, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x45125641 | vkCmdBeginRenderPass(): Image view #0 created from an image with usage set as 0x11, but image info #0 used to create the framebuffer had usage set as 0x10 The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with an inherited usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.2.189.2/windows/1.2-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-04627)
    object info: (type: RENDER_PASS, hndl: 13371743646546657316)
```

And it's printed regardless of whether I add the `EguiPlugin` plugin or not.

Which version of Vulkan SDK do you use? (I have `1.2.189.2` installed, and I also test on Windows 10.)

**Comment by RichMQ** [comment] 2021-10-04 20:29
I've got 1.2.189.2 as well. Is there anything I can do on my end to diagnose the issue closer?

**Comment by mvlabat** [comment] 2021-10-05 21:58
Closed this by mistake. Sorry!

**Comment by mvlabat** [comment] 2021-10-18 10:03
Hey @RichMQ, sorry that it took me so long to actually answer your question. I don't know much about rendering and Vulkan, but after talking to other developers, we came up to a conclusion that it might be a problem on a lower level: either Bevy, WGPU or anything else. Unfortunately, no one else who I know could also reproduce the issue, so it's difficult to be confident here.

One of the things that I wanted to ask you to try is to run the example on the `bevy_egui` branch that is built on the new renderer (it also uses a newer version of WGPU): https://github.com/jakobhellermann/bevy_egui/tree/bevy-pipelined.

Could you please try the example on that one and check if you can see the same validation errors?

**Comment by mvlabat** [comment] 2021-10-18 15:50
> but maybe that example is no longer expected to work on this branch

Yeah, I haven't tried this branch myself yet, but I think you're right, only `simple_pipelined.rs` is supposed to work.

> Does bevy-pipelined refer to the new renderer in bevy 0.6?

That's correct.

DirectX warnings seem like a WGPU issue as well. Btw, could you also try to switch the backend back to Vulkan, to see that those validation errors are gone indeed? I believe with the pipelined-rendering branch you can now do it by setting an environment variable: `WGPU_BACKEND=vulkan`.

**Comment by mvlabat** [comment] 2022-01-15 10:07
Closing this as Bevy 0.6 is released now and we support it.

**Closed by mvlabat** 2022-01-15 10:07 UTC
