### ISSUE TITLE
How do you stop a click registering in bevy when I click on egui?

### ISSUE THREAD

**Issue by FVellu** [mvlabat/bevy_egui#187] opened 2023-06-18 09:58 UTC
I have a painting app, but when I click the bevy ui, it also paints the pixel "behind" egui. How can I prevent this?

**Comment by opfromthestart** [comment] 2023-06-30 03:38
`!egui_ctx.single_mut().get_mut().is_pointer_over_area()` as a condition is what I use and it works well.

**Comment by Youdiie** [comment] 2023-07-12 10:53
@opfromthestart 
I used [bevy_transform_gizmo](https://github.com/ForesightMiningSoftwareCorporation/bevy_transform_gizmo) to move object in bevy, and wanted to stop a click in bevy when I click on egui. Using `egui_ctx.single_mut().get_mut().is_pointer_over_area()`, I get a condition mouse on ui, but I don't know how to stop a click. Can you help me?

**Comment by mvlabat** [comment] 2023-07-12 14:15
Hey @FVellu, sorry for the delayed answer. I'll close the issue as a duplicate of #47. Basically, the discussion there mentions the same workaround that @opfromthestart brought up, and that issue is also tracking a finer solution that depends on (yet to be made) changes to Bevy.

**Closed by mvlabat** 2023-07-12 14:15 UTC
