### ISSUE TITLE
bevy games integration in canvas

### ISSUE THREAD

**Issue by pyweeker** [mvlabat/bevy_egui#58] opened 2022-01-17 15:39 UTC
hello,
how can i replace painting example by this simple breakout example
https://github.com/bevyengine/bevy/blob/main/examples/game/breakout.rs
and keep the rest of the interface ?

i'd like to display widgets like this around the canvas
https://cdn.cloudflare.steamstatic.com/steam/apps/6010/ss_1efdc683240bfff2f7293388dad94fc47c233d35.1920x1080.jpg?t=1571778027

https://d3isma7snj3lcx.cloudfront.net/optim/images/photos/00/00/01/13/tres-peu-de-surprises-parmi-les-constructions-disponibles-ME0000011334_2__w830.jpg

**Comment by mvlabat** [comment] 2022-01-19 20:39
Hi! I believe this is a duplicate of #30. I don't have a ready example yet, but since there appears to be a high demand for it, I'll try to come up with something sooner. Meanwhile, you can also ask around in Bevy [discussions](https://github.com/bevyengine/bevy/discussions) or [Discord](https://discord.gg/bevy), as it's a problem not unique to `bevy_egui` but relates to every game with this kind of UI.

Unfortunately, I can't give any advice atm, apart from what I've mentioned in #30, as I haven't quite explored this problem myself yet.

**Closed by mvlabat** 2022-01-19 20:39 UTC

**Comment by pyweeker** [comment] 2022-01-19 23:05
hi Vladyslav,
i found this , it can help you too

https://github.com/pyweeker/bevy_egui_paneled_playground

bye

Christophe
